# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

group :development do
  gem "solargraph", "~> 0.39.17"
end

group :development, :test do
  gem "rspec", "~> 3.10"
end
